[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
loader = { path = "../loader" }
parser = { path = "../parser" }

simple-error = "0.3"
log = "0.4.17"
lazy_static = "1.4.0"