[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
parser = { path = "../parser" }
loader = { path = "../loader" }

clap = { version = "3.1.2", features = ["derive"] }
prettytable-rs = "0.8.0"