[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
parser = { path = "../parser" }

glob = "0.3.1"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
anyhow = "1.0"

[dev-dependencies]
