[package]
name = "loader"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
parser = { path = "../parser" }

glob = "0.3.0"
zip = { version = "0.5", default-features = false, features = ["deflate"] }
simple-error = "0.2"

[dev-dependencies]
