name: Rust Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build

    - name: Fetch Java Runtime
      run: ./fetch_runtime.sh

    - name: Run tests
      run: cargo test

    - name: Check format
      run: cargo fmt --all -- --check
